#!/bin/bash
path=$1           #path to results e.g. /home/foo/bar/raw
destination=$2    #path of app raw dir e.g. foo@bar:/home/foo/bar/raw
ip_service=$3     #ip of cluster login e.g. xxx.xxx.xxx.xxx
port=$4           #usable ssh port of cluster login e.g. 8080

./src/ssupervisor_sinfo1 "$path/ssupervisor_sinfo1.txt" $destination $port &> /dev/null
./src/ssupervisor_sinfo2 "$path/ssupervisor_sinfo2.txt" $destination $port &> /dev/null
./src/ssupervisor_sinfo3 "$path/ssupervisor_sinfo3.txt" $destination $port &> /dev/null
./src/ssupervisor_squeue1 "$path/ssupervisor_squeue1.txt" $destination $port &> /dev/null
./src/ssupervisor_dfh1 "$path/ssupervisor_dfh1.txt" $destination $port &> /dev/null
./src/ssupervisor_ping $ip_service "$path/ssupervisor_ping.txt" $destination $port &> /dev/null
./src/ssupervisor_s0cpu "$path/ssupervisor_s0cpu.txt" $destination $port &> /dev/null
