#!/bin/bash
file=$1
destination=$2
port=$3

echo $(date "+%d/%m/%y %T")  > $file
echo EMAIL >> $file

echo "[sinfo --state=down -o %D] Down nodes" >> $file
sinfo --state=down -o %D >> $file
echo $'#  #\n' >> $file

scp -P $port $file $destination
