#!/bin/bash
file=$1
destination=$2
port=$3

echo $(date "+%d/%m/%y %T")  > $file

echo "[sinfo -R] Down nodes explanation" >> $file
sinfo -R >> $file
echo $'#  #' >> $file

scp -P $port $file $destination
