#!/bin/bash
file=$1
destination=$2
port=$3

echo $(date "+%d/%m/%y %T") > $file

echo "[s0cpu] CPU usage of service0" >> $file
python cpuUsage.py >> $file
echo $'#  #' >> $file

scp -P $port $file $destination
