#!/bin/bash
file=$1
destination=$2
port=$3

echo $(date "+%d/%m/%y %T") > $file

echo "[squeue] Information about jobs located in the Slurm scheduling queue" >> $file
squeue >> $file
echo $'#  #' >> $file

scp -P $port $file $destination
