#!/bin/bash
file=$1
destination=$2
port=$3

echo $(date "+%d/%m/%y %T")  > $file

echo "[sinfo] General Information about nodes and partitions for a system running Slurm" >> $file
sinfo >> $file
echo $'#  #' >> $file

scp -P $port $file $destination
