#!/bin/bash

echo $(date "+%d/%m/%y %T")  > /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_ping.txt
echo EMAIL >> /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_ping.txt

echo "[ping -c 4 10.7.32.67] Ping service0" >> /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_ping.txt
ping -c 4 10.7.32.67 >> /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_ping.txt
echo $'#  #\n' >> /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_ping.txt

scp -P 4422 /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_ping.txt adelsonNPAD@10.7.8.74:/var/www/html/protected/tmp/supervisor/raw
