#!/bin/bash

echo $(date "+%d/%m/%y %T") > /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_squeue1.txt

echo "[squeue] Information about jobs located in the Slurm scheduling queue" >> /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_squeue1.txt
squeue >> /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_squeue1.txt
echo $'#  #' >> /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_squeue1.txt

scp -P 4422 /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_squeue1.txt adelsonNPAD@10.7.8.74:/var/www/html/protected/tmp/supervisor/raw
