#!/bin/bash

echo $(date "+%d/%m/%y %T")  > /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_sinfo2.txt

echo "[sinfo -R] Down nodes explanation" >> /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_sinfo2.txt
sinfo -R >> /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_sinfo2.txt
echo $'#  #' >> /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_sinfo2.txt

scp -P 4422 /home/adelsonNPAD/learning/project/supervisoring/raw/ssupervisor_sinfo2.txt adelsonNPAD@10.7.8.74:/var/www/html/protected/tmp/supervisor/raw
