#!/bin/bash
service0_IP=$1
file=$2
destination=$3
port=$4

echo $(date "+%d/%m/%y %T")  > $file
echo EMAIL >> $file

echo "[ping -c 4 $service0_IP] Ping service" >> $file
ping -c 4 $service0_IP >> $file
echo $'#  #\n' >> $file

scp -P $port $file $destination

